version: "3"
services:
    web:
        #image: 'gadgeonkoreonepoc_web'
        build: './Poc.Api'
        ports:
            - 5000:5000
        #env:
        #- name: cassandra-endpoint
        #  value: "localhost:000"
        #- name: elastic-endpoint
        #  value: "localhost:000"
    ui:
        #image: 'gadgeonkoreonepoc_ui'
        build: 
            context: './Lbs.UI'
            dockerfile: KafkaManager/Dockerfile
        ports:
            - 3000:80
        #env:
        #- name: cassandra-endpoint
    signalr:
        #image: 'gadgeonkoreonepoc_signalr'
        build: 
            context: './SignalR-Hub'
            dockerfile: 
        ports:
            - 5001:5001
            version: '3.4'

    kafkamanager:
        image: poc_kafkamanager
        build:
            context: KafkaManager
            dockerfile: KafkaManager/KafkaManager/Dockerfile
